# Generated by Django 5.2.8 on 2025-11-11 10:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido (7-15 dígitos, opcional +).', regex='^\\+?\\d{7,15}$')])),
                ('direccion', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido (7-15 dígitos, opcional +).', regex='^\\+?\\d{7,15}$')])),
                ('aprobado', models.BooleanField(default=False)),
                ('marcas', models.ManyToManyField(blank=True, related_name='mecanicos', to='aplicacionTaller.marca')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_mecanico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_trabajo', models.TextField()),
                ('costo_final', models.CharField(max_length=45)),
                ('fecha_realizacion', models.DateField()),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionTaller.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('motivo', models.TextField(verbose_name='Motivo de la Cita (Síntomas)')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Aprobación'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=45)),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to='aplicacionTaller.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
                ('costo', models.IntegerField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='aplicacionTaller.cita')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionTaller.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=45, unique=True)),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('año', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='aplicacionTaller.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='aplicacionTaller.vehiculo'),
        ),
    ]
