# Generated by Django 5.2.8 on 2025-11-11 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25, unique=True)),
                ('contrasenia', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=60)),
                ('direccion', models.CharField(max_length=45)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacionTaller.login')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('especialidad', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacionTaller.login')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_trabajo', models.CharField(max_length=80)),
                ('costo_final', models.CharField(max_length=45)),
                ('fecha_realizacion', models.DateField()),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionTaller.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('costo', models.IntegerField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionTaller.cita')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionTaller.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=45, unique=True)),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('año', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionTaller.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionTaller.vehiculo'),
        ),
    ]
