# Generated by Django 5.2.5 on 2025-10-19 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('Motor', 'Motor'), ('Frenos', 'Frenos'), ('Suspensión', 'Suspensión'), ('Eléctrico', 'Eléctrico'), ('Transmisión', 'Transmisión'), ('Neumáticos', 'Neumáticos'), ('Diagnóstico', 'Diagnóstico Electrónico'), ('Mantenimiento', 'Mantenimiento General')], max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_mecanico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
